# Generated by Django 5.0.1 on 2024-01-22 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_image_product_thumnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='thumnail',
            new_name='thumbnail',
        ),
    ]
